const products={move:{type:'ALL-DAY CUSHIONING · SECURE FIT',title:'Move Clog',copy:'Your easy-on everyday clog for coffee runs, campus miles, travel days and everything between.',fit:'Roomy through the toe with a considered heel cup and stable platform. Final size guidance will follow U.S. fit trials.',image:'yooyos-move-clog-v2.png',colors:['#a84f3e','#8d9877','#e3d4bd','#202321']},flow:{type:'WATER-FRIENDLY · EASY TO CLEAN',title:'Flow Slide',copy:'Your quick-drying slide for easy transitions from the pool or gym to the rest of your day.',fit:'A comfortable strap geometry and contoured footbed are being developed to hold without pinching. Final size guidance is pending.',image:'yooyos-flow-slide-v2.png',colors:['#d8c3a3','#1f211f','#afc8c4','#a84f3e']},duo:{type:'LIGHTWEIGHT · ADJUSTABLE FIT',title:'Duo Sandal',copy:'Your light, adjustable two-band sandal for markets, beach walks and warm-weather weekends.',fit:'Two adjustment points are intended to accommodate different foot volumes. Final size guidance will follow U.S. fit trials.',image:'yooyos-duo-sandal-v2.png',colors:['#8d9877','#d8c3a3','#1f211f','#cf8a77']}};
const header=document.querySelector('header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20),{passive:true});
const menu=document.querySelector('.menu'),mobile=document.querySelector('.mobile-nav');menu.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',open);mobile.setAttribute('aria-hidden',!open)});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const backdrop=document.querySelector('.backdrop'),drawer=document.querySelector('.drawer'),inquiry=document.querySelector('.inquiry');function show(target){target.classList.add('open');target.setAttribute('aria-hidden','false');backdrop.hidden=false;document.body.classList.add('locked')}function close(){drawer.classList.remove('open');inquiry.classList.remove('open');drawer.setAttribute('aria-hidden','true');inquiry.setAttribute('aria-hidden','true');backdrop.hidden=true;document.body.classList.remove('locked')}
document.querySelectorAll('.product-card').forEach(card=>card.querySelector('.quick').addEventListener('click',()=>{const p=products[card.dataset.product];drawer.querySelector('img').src=p.image;drawer.querySelector('img').alt=p.title+' concept';drawer.querySelector('.dtype').textContent=p.type;drawer.querySelector('h2').textContent=p.title;drawer.querySelector('.dcopy').textContent=p.copy;drawer.querySelector('.dfit').textContent=p.fit;drawer.querySelector('.swatches').innerHTML=p.colors.map(c=>`<span style="background:${c}"></span>`).join('');show(drawer)}));
document.querySelector('.close').addEventListener('click',close);document.querySelector('.close-i').addEventListener('click',close);backdrop.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.querySelectorAll('.open-inquiry,.interest').forEach(b=>b.addEventListener('click',()=>{drawer.classList.remove('open');show(inquiry)}));
document.querySelector('.signup form').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.closest('.signup').classList.add('done')});document.querySelector('.inquiry form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),s=encodeURIComponent(`YOOYOS ${d.get('interest')} inquiry — ${d.get('company')}`),b=encodeURIComponent(`Name: ${d.get('name')}\nEmail: ${d.get('email')}\nCompany / store: ${d.get('company')}\nInterest: ${d.get('interest')}\nRetail locations: ${d.get('locations')}\nOpening order interest: ${d.get('order')}\n\n${d.get('message')||''}`);location.href=`mailto:hello@yooyos.com?subject=${s}&body=${b}`});
const mobileLaunch=document.querySelector('.mobile-launch-form');mobileLaunch.addEventListener('submit',e=>{e.preventDefault();const email=mobileLaunch.querySelector('input').value;const signup=document.querySelector('.signup');signup.querySelector('input').value=email;location.hash='connect';signup.querySelector('input').focus()});
