const products={move:{type:'01 / THE EVERYDAY HERO',title:'Move Clog',copy:'A secure, easy-on clog made for morning coffee, campus miles, dog walks and the five-minute errand that becomes an afternoon.',fit:'Roomy through the toe with a considered heel cup and stable platform. Final sizing will be informed by U.S. fit trials.',image:'yooyos-move-clog-v2.png',colors:['#a84f3e','#8d9877','#e3d4bd','#202321']},flow:{type:'02 / THE EASY-ON ESSENTIAL',title:'Flow Slide',copy:'A broad-strap, water-friendly slide designed to move naturally between pool deck, gym bag, hotel breakfast and home.',fit:'A comfortable strap geometry and contoured footbed are being developed to hold without pinching.',image:'yooyos-flow-slide-v2.png',colors:['#d8c3a3','#1f211f','#afc8c4','#a84f3e']},duo:{type:'03 / THE SUNNY-DAY ALL-ROUNDER',title:'Duo EVA Sandal',copy:'Two adjustable bands bring a more intentional fit to an easy, water-friendly warm-weather shape.',fit:'Two adjustment points accommodate different foot volumes while the heel cup and gentle contour guide the foot.',image:'yooyos-duo-sandal-v2.png',colors:['#8d9877','#d8c3a3','#1f211f','#cf8a77']}};
const header=document.querySelector('header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20),{passive:true});
const menu=document.querySelector('.menu'),mobile=document.querySelector('.mobile-nav');menu.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',open);mobile.setAttribute('aria-hidden',!open)});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const tabs=[...document.querySelectorAll('.ctab')],detail=document.querySelector('.comfort-detail');tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');detail.innerHTML=`<span>${tab.dataset.title}</span><p>${tab.dataset.copy}</p>`}));
const backdrop=document.querySelector('.backdrop'),drawer=document.querySelector('.drawer'),inquiry=document.querySelector('.inquiry');function show(target){target.classList.add('open');target.setAttribute('aria-hidden','false');backdrop.hidden=false;document.body.classList.add('locked')}function close(){drawer.classList.remove('open');inquiry.classList.remove('open');drawer.setAttribute('aria-hidden','true');inquiry.setAttribute('aria-hidden','true');backdrop.hidden=true;document.body.classList.remove('locked')}
document.querySelectorAll('.product-card').forEach(card=>card.querySelector('.quick').addEventListener('click',()=>{const p=products[card.dataset.product];drawer.querySelector('img').src=p.image;drawer.querySelector('img').alt=p.title+' concept';drawer.querySelector('.dtype').textContent=p.type;drawer.querySelector('h2').textContent=p.title;drawer.querySelector('.dcopy').textContent=p.copy;drawer.querySelector('.dfit').textContent=p.fit;drawer.querySelector('.swatches').innerHTML=p.colors.map(c=>`<span style="background:${c}"></span>`).join('');show(drawer)}));
document.querySelector('.close').addEventListener('click',close);document.querySelector('.close-i').addEventListener('click',close);backdrop.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.querySelectorAll('.open-inquiry,.interest').forEach(b=>b.addEventListener('click',()=>{drawer.classList.remove('open');show(inquiry)}));
document.querySelector('.signup form').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.closest('.signup').classList.add('done')});document.querySelector('.inquiry form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),s=encodeURIComponent(`YOOYOS inquiry — ${d.get('interest')}`),b=encodeURIComponent(`Name: ${d.get('name')}\nEmail: ${d.get('email')}\nInterest: ${d.get('interest')}\n\n${d.get('message')||''}`);location.href=`mailto:hello@yooyos.com?subject=${s}&body=${b}`});
